[package]
name = "white-whale-std"
version = "1.1.3"
edition.workspace = true
authors = [
  "Kerber0x <kerber0x@protonmail.com>",
  "0xFable <0xfabledev@gmail.com>",
  "kaimen-sano <kaimen_sano@protonmail.com>",
  "White Whale <info@whitewhale.money>",
]
description = "Common White Whale types and utils"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

[features]
default = ["osmosis_token_factory"]
injective = ["token_factory"]
osmosis = ["osmosis_token_factory"]
token_factory = []
osmosis_token_factory = [
  "token_factory",
] # this is for the osmosis token factory proto definitions, which defer from the standard token factory :)
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std.workspace = true
schemars.workspace = true
serde.workspace = true
cosmwasm-schema.workspace = true
cw-storage-plus.workspace = true
cw20.workspace = true
cw2.workspace = true
protobuf.workspace = true
uint.workspace = true
osmosis-std-derive.workspace = true
prost.workspace = true
prost-types.workspace = true
cw-ownable.workspace = true
anybuf.workspace = true
cw-controllers.workspace = true
anyhow.workspace = true
thiserror.workspace = true

[dev-dependencies]
cw-multi-test.workspace = true
