[package]
name = "vault-network"
version = "1.0.1"
edition = "2021"
homepage = "https://whitewhale.money"
license = "MIT"
repository = "https://github.com/White-Whale-Defi-Platform/migaloo-core"
authors = ["kaimen-sano <kaimen_sano@protonmail.com>"]
description = "Messages for the Vault Network"
documentation = "https://whitewhale.money"

[dependencies]
cosmwasm-std.workspace = true
terraswap.workspace = true
serde.workspace = true
schemars.workspace = true
white-whale = { path = "../white-whale" }
cosmwasm-schema.workspace = true
