[package]
name = "white-whale-testing"
version = "1.0.0"
edition.workspace = true
authors = ["Kerber0x <kerber0x@protonmail.com>"]
description = "Common White Whale types and utils for testing"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://whitewhale.money"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
default = ["osmosis_token_factory"]
backtraces = ["cosmwasm-std/backtraces"]

injective = ["token_factory"]
token_factory = []

osmosis = ["osmosis_token_factory"]
osmosis_token_factory = ["token_factory"]

[dependencies]
anyhow.workspace = true
cosmwasm-std.workspace = true
schemars.workspace = true
serde.workspace = true
cosmwasm-schema.workspace = true
cw-multi-test.workspace = true
white-whale-std.workspace = true
whale-lair.workspace = true
fee_collector.workspace = true
fee_distributor.workspace = true
