[package]
name = "cw1155"
version = "1.0.0"
authors = ["Huang Yi <huang@crypto.com>", "0xFable <0xfable@protonmail.com>"]
edition = "2018"
description = "Definition and types for the CosmWasm-1155 interface"
license = "MIT"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"

[dependencies]
cw-utils.workspace = true
cosmwasm-schema.workspace = true
cosmwasm-std.workspace = true
schemars.workspace = true
serde.workspace = true
