[package]
name = "fee_collector"
version = "1.1.0"
authors = ["Kerber0x <kerber0x@protonmail.com>"]
edition = "2021"
homepage = "https://whitewhale.money"
license = "MIT"
repository = "https://github.com/White-Whale-Defi-Platform/migaloo-core"
publish = false
description = "Contract to collect the fees accrued by the pools and vaults in the liquidity hub"
documentation = "https://whitewhale.money"

exclude = [
	# Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
	"contract.wasm",
	"hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
injective = ["terraswap/injective"]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std.workspace = true
cw2.workspace = true
cw20.workspace = true
cw-storage-plus.workspace = true
schemars.workspace = true
semver.workspace = true
serde.workspace = true
thiserror.workspace = true
white-whale = { path = "../../../packages/white-whale" }
terraswap = { path = "../../../packages/terraswap" }
vault-network = { path = "../../../packages/vault-network" }
cosmwasm-schema.workspace = true

[dev-dependencies]
cw-multi-test = "0.15.1"
terraswap-router = { path = "../pool-network/terraswap_router" }
terraswap-factory = { path = "../pool-network/terraswap_factory" }
terraswap-pair = { path = "../pool-network/terraswap_pair" }
stableswap-3pool = { path = "../pool-network/stableswap_3pool" }
terraswap-token = { path = "../pool-network/terraswap_token" }
vault_factory = { version = "1.0.0", path = "../vault-network/vault_factory" }
vault = { version = "1.0.0", path = "../vault-network/vault" }
cw20 = { version = "0.15.1" }
