[package]
name = "vault_factory"
version = "1.1.1"
authors = [
	"kaimen-sano <kaimen_sano@protonmail.com>, Kerber0x <kerber0x@protonmail.com>",
]
edition = "2021"
homepage = "https://whitewhale.money"
license = "MIT"
repository = "https://github.com/White-Whale-Defi-Platform/migaloo-core"
publish = false
description = "Contract to facilitate the vault network"
documentation = "https://whitewhale.money"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
injective = ["terraswap/injective"]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std.workspace = true
cw2.workspace = true
cw20.workspace = true
cw-storage-plus.workspace = true
protobuf.workspace = true
schemars.workspace = true
semver.workspace = true
serde.workspace = true
terraswap = { path = "../../../../packages/terraswap" }
thiserror.workspace = true
vault-network = { path = "../../../../packages/vault-network" }
white-whale = { path = "../../../../packages/white-whale" }
cosmwasm-schema.workspace = true

[dev-dependencies]
cw-multi-test = "0.15.1"
cw20-base = "0.15.1"
vault = { path = "../vault" }
fee_collector = { path = "../../fee_collector" }
