[package]
name = "vault"
version = "1.2.1"
authors = ["kaimen-sano <kaimen_sano@protonmail.com>"]
edition = "2021"
homepage = "https://whitewhale.money"
license = "MIT"
repository = "https://github.com/White-Whale-Defi-Platform/migaloo-core"
publish = false
description = "Contract to handle a single vault that controls an asset"
documentation = "https://whitewhale.money"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
injective = ["terraswap/injective"]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std.workspace = true
cosmwasm-schema.workspace = true
cw2.workspace = true
cw20.workspace = true
cw20-base.workspace = true
cw-storage-plus.workspace = true
protobuf.workspace = true
schemars.workspace = true
semver.workspace = true
serde.workspace = true
terraswap = { path = "../../../../packages/terraswap" }
thiserror.workspace = true
vault-network = { path = "../../../../packages/vault-network" }
white-whale = { path = "../../../../packages/white-whale" }

[dev-dependencies]
cosmwasm-schema = "1.1.4"
cw-multi-test = "0.15.1"
fee_collector = { path = "../../fee_collector" }
