[package]
name = "vault"
version = "1.0.0"
authors = ["kaimen-sano <kaimen_sano@protonmail.com>"]
edition = "2021"
description = "Contract to handle a single vault that controls an asset"
license = "MIT"
repository = "https://github.com/White-Whale-DeFi-Platform/migaloo-core"
homepage = "https://whitewhale.money"
documentation = "https://whitewhale.money"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "1.0.0", features = ["iterator"] }
cw2 = "0.13.4"
cw20 = "0.13.4"
cw-storage-plus = "0.13.4"
schemars = "0.8.3"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
terraswap = { git = "https://github.com/terraswap/terraswap.git", tag = 'v2.7.0'}
thiserror = "1.0.21"
vault-network = { path = "../../../../packages/vault-network" }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0" }
