name: Validate schemas

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate_schemas:
    name: Validate schemas are up to date
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable

      - name: Validate schemas are up to date
        run: ./scripts/build_schemas.sh -d true

      - name: Add comment if failed
        if: ${{ failure() }}
        uses: actions/github-script@v7
        with:
          script: |
            const { execSync } = require("child_process");

            const diffSchemas = execSync(
              'git ls-files --modified --others --exclude-standard "*.json"',
              { encoding: "utf-8" }
            ).trim();

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Schema generation had missing jobs:\n```${diffSchemas}````\nPlease run `just schemas` locally and upload the generated schemas.'
            })
